oplash/apps/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import ProfileFollowView, ProfileView, RegisterView, SettingView

urlpatterns = [
    path(
        "register/",
        RegisterView.as_view(redirect_authenticated_user=True),
        name="register",
    ),
    path("login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("settings/", SettingView.as_view(), name="settings"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path("profile/follow/<int:pk>/", ProfileFollowView.as_view(), name="follow"),
]

oplash/apps/articles/urls.py
from django.urls import path

from .views import (
    ArticleCreateView,
    ArticleDeleteView,
    ArticleDetailView,
    ArticleFavoriteView,
    ArticleListView,
    ArticleUpdateView,
)
from .views import Search

app_name = "articles"

urlpatterns = [
    path("", ArticleListView.as_view(), name="list"),
    path("new/", ArticleCreateView.as_view(), name="create"),
    path(
        "article/<int:pk>/<slug:slug>/",
        ArticleDetailView.as_view(),
        name="detail",
    ),
    path(
        "article/edit/<int:pk>/",
        ArticleUpdateView.as_view(),
        name="edit",
    ),
    path(
        "article/delete/<int:pk>/",
        ArticleDeleteView.as_view(),
        name="delete",
    ),
    path(
        "article/favorite/<int:pk>/",
        ArticleFavoriteView.as_view(),
        name="favorite",
    ),
    
    path("search/", Search, name='search'),
]

oplash/apps/comments/urls.py
from django.urls import path

from .views import CommentDeleteView

app_name = "comments"

urlpatterns = [path("delete/<int:pk>/", CommentDeleteView.as_view(), name="delete")]

oplash/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from oplash.apps.articles.views import Search
from filebrowser.sites import site
from django_comments.feeds import LatestCommentFeed

urlpatterns = [
     path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),
    path("", include("oplash.apps.articles.urls")),
    path("", include("oplash.apps.accounts.urls")),
    path("comments/", include("oplash.apps.comments.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path("search/", Search, name='search'),
    path('comments/', include('django_comments.urls')),
    path('feeds/latest/', LatestCommentFeed()),
]

"""if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]"""

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oplash/apps/accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.urls import reverse


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError("The Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    # remove default fields
    username = None
    first_name = None
    last_name = None

    email = models.EmailField("Email address", unique=True)
    name = models.CharField(max_length=60)
    bio = models.TextField(blank=True)
    image = models.ImageField()

    following = models.ManyToManyField(
        "self", blank=True, related_name="followers", symmetrical=False
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("profile", args=[self.id])

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

oplash/apps/comments/models.py
from django.conf import settings
from django.db import models

from oplash.apps.articles.models import Article


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    content = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content[:50]

oplash/apps/core/models.py
from django.db import models

# Create your models here.

oplash/apps/accounts/forms.py
from django.contrib.auth import password_validation
from django.forms import CharField, ModelForm, PasswordInput

from .models import User


class UserCreationForm(ModelForm):
    password = CharField(
        label="Password",
        strip=False,
        widget=PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )

    class Meta:
        model = User
        fields = ["email", "name"]

    def save(self, commit: bool = True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class SettingsForm(ModelForm):
    password = CharField(
        label="Password",
        strip=False,
        required=False,
        widget=PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )

    class Meta:
        model = User
        fields = ["email", "name", "bio", "image"]

    def save(self, commit: bool = True):
        user = super().save(commit=False)
        if self.cleaned_data["password"]:
            user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

oplash/apps/articles/forms.py
from dataclasses import fields
from django import forms

from .models import Article

from tinymce.widgets import TinyMCE


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class ArticleForm(forms.ModelForm):
    
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows':20}
            )
    )
    class Meta:
        model = Article
        fields = '__all__'

"""
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "summary", "content", "tags", "featured", "thumbnail", "next_article", "previous_article", "status"]
        widgets = {"summary": forms.TextInput()}
"""

oplash/apps/comments/forms.py
from django.forms import ModelForm

from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

oplash/apps/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import CreateView, ListView, UpdateView

from oplash.apps.articles.models import Article

from .forms import SettingsForm, User, UserCreationForm


class ProfileView(ListView):
    context_object_name = "articles"
    template_name = "oplash/accounts/profile.html"

    def get_queryset(self):
        profile = get_object_or_404(User, pk=self.kwargs["pk"])
        articles = (
            Article.objects.select_related("author")
            .with_favorites(self.request.user)
            .prefetch_related("tags")
            .order_by("-created")
        )

        if "favorites" in self.request.GET:
            return articles.filter(is_favorite=True)

        return articles.filter(author=profile)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = get_object_or_404(User, pk=self.kwargs["pk"])
        context["profile"] = profile
        context["is_following"] = profile.following.filter(
            pk=self.request.user.id
        ).exists()
        return context


class SettingView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = SettingsForm
    template_name = "oplash/accounts/settings.html"

    def get_object(self):
        return get_object_or_404(User, id=self.request.user.id)


class RegisterView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = "registration/register.html"
    redirect_authenticated_user = False

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a register page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        valid = super().form_valid(form)
        login(self.request, self.object)
        return valid

    def get_success_url(self):
        return '/'


class ProfileFollowView(LoginRequiredMixin, UpdateView):
    fields = ["following"]
    http_method_names = ["post"]

    def get_queryset(self, **kwargs):
        return User.objects.filter(pk=self.kwargs["pk"]).exclude(
            pk=self.request.user.id
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.following.filter(id=request.user.id).exists():
            self.object.following.remove(request.user)
        else:
            self.object.following.add(request.user)

        return redirect(self.object.get_absolute_url())

oplash/apps/articles/views.py
from multiprocessing import context
from turtle import title
from django.forms import SlugField
from django.shortcuts import redirect
from django.test import tag
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)


from django.db.models import Q
from taggit.models import Tag
from django.shortcuts import render
from oplash.apps.comments.forms import Comment, CommentForm
from oplash.apps.core.mixins import AuthorRequiredMixin, LoginRequiredMixin

from .forms import Article, ArticleForm

def Search(request):
    template_name = "oplash/articles/search_results.html"
    queryset = Article.objects.all()
    query = request.GET.get('s')
    if query:
        queryset = queryset.filter(Q(title__icontains=query) | Q(summary__icontains=query)).distinct()

    context ={
        "queryset": queryset
    }
  
    return render(request, template_name, context)


class ArticleListView(ListView):
    context_object_name = "articles"
    template_name = "oplash/articles/article_list.html"

    def get_queryset(self):
        queryset = (
            Article.objects.select_related("author")
            .get_published()
            .with_favorites(self.request.user)
            .prefetch_related("tags")
            .order_by("-created")
        )

        if tag := self.request.GET.get("tag"):
            return queryset.filter(tags__name__in=[tag])

        if self.request.user.is_authenticated and "own" in self.request.GET:
            return queryset.filter(author=self.request.user)

        return queryset
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tags"] = Tag.objects.all()
        context['latest'] = Article.objects.get_published().order_by('-created')[0:4]
        context['featured'] = Article.objects.get_published().filter(featured=True).order_by('featured')[0:2]
        return context


class ArticleDetailView(DetailView):
    context_object_name = "article"
    template_name = "oplash/articles/article_detail.html"

    def get_queryset(self):
        queryset = Article.objects.select_related("author").with_favorites(
            self.request.user
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        is_following = self.object.author.following.filter(
            pk=self.request.user.id
        ).exists()
        comments = (
            Comment.objects.filter(article=self.kwargs["pk"])
            .select_related("author")
            .order_by("-created")
        )

        context["is_following"] = is_following
        context["tags"] = Tag.objects.all()
        context["comments"] = comments
        context["comment_form"] = CommentForm()
        context['related']=Article.objects.prefetch_related("tags").order_by("?")[0:4]
        return context

    def post(self, request, *args, **kwargs):
        comment = Comment(
            content=request.POST.get("content"),
            author=self.request.user,
            article=self.get_object(),
        )
        comment.save()
        return self.get(self, request, *args, **kwargs)


class ArticleCreateView(AuthorRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm
    template_name = "oplash/articles/article_form.html"

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        article.save()

        # save tags
        form.save_m2m()

        return super().form_valid(form)


class ArticleUpdateView(AuthorRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = "oplash/articles/article_form.html"


class ArticleDeleteView(AuthorRequiredMixin, DeleteView):
    model = Article
    success_url = "/"


class ArticleFavoriteView(LoginRequiredMixin, UpdateView):
    fields = ["favorites"]
    http_method_names = ["post"]

    def get_queryset(self):
        return Article.objects.select_related("author").exclude(
            author=self.request.user
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.favorites.filter(id=request.user.id).exists():
            self.object.favorites.remove(request.user)
        else:
            self.object.favorites.add(request.user)

        return redirect(self.object.get_absolute_url())

oplash/apps/comments/views.py
from django.views.generic import DeleteView

from oplash.apps.core.mixins import AuthorRequiredMixin

from .models import Comment


class CommentDeleteView(AuthorRequiredMixin, DeleteView):
    model = Comment
    success_url = "/"

oplash/apps/core/views.py
from django.shortcuts import render

# Create your views here.

oplash/templates/oplash/articles/partials/article.html
{% load static %}
{% load comments %}
<div class="col-lg-6 col-md-4">
  <div class="card shadow-sm">
    <div class="card-header d-flex justify-content-between align-items-center">
      {% get_comment_count for article as comment_count %}

      <div class="comment"><i class="bi-chat"></i> {{ comment_count}}</div>
      <small class="text-muted">{{article.get_readtime}} mins</small>
    </div>
    <a class="text-black" href="{{ article.get_absolute_url }}"><img class="bd-placeholder-img card-img-top"
        src="{{ article.thumbnail.url }}" width="100%" height="225" alt="article image"></a>

    <div class="card-body">
      <h4 class="card-text"><a class="text-black" href="{{ article.get_absolute_url }}">{{ article.title | truncatechars:55}}</a></h4>
      <p class="card-text">{{ article.summary | truncatechars:170 }} </p>

      <footer class="post-footer d-flex justify-content-between align-items-center">
        <a class="author d-flex align-items-center flex-nowrap">
          <div class="avater" style="max-width: 30px;
        min-width: 30px;
        height: 30px;
        overflow: hidden;
        border-radius: 50%;
        margin-right: 3px;">
            {% if article.author.image %}

            <div class=""><img class="rounded-circle" src="{{ article.author.image.url }}" width="30" height="30"
                style="border:1px solid gray">
              <small>{{article.author}}</small>
            </div>
            {% else %}

            <div><img class="rounded-circle" src="{% static '/img/profile.png' %}" width="30" height="30"
                alt="user profile image">
              <span>{{article.author}}</span>
            </div>
            {% endif %}

          </div>

          <div class="title"><span><em> {{article.author}} </em></span></div>
        </a>
        <div class="date"> <i class="bi-clock"></i> {{ article.created | timesince}} ago</div>


        <div class="btn-group">
          <!--<a href="{{ article.get_absolute_url }}"><button type="button" class="btn btn-sm btn-outline-secondary">View</button></a>-->
          <!--<a href="{{ article.get_absolute_url }}"><button type="button" class="btn btn-sm btn-outline-secondary"><i class="bi-heart"></i></button></a>-->
          {% include "oplash/articles/partials/small_favorite_btn.html" with num_favorites=article.num_favorites is_favorite=article.is_favorite %}

        </div>

      </footer>
      <!-- {% with tags=article.tags.all %}
        {% if tags %}
          <div class="card-footer">
            {% for tag in tags %}
              <small class="text-muted">
                <a class="text-muted" href="{% url 'articles:list' %}?tag={{ tag.name }}">{{ tag }} |</a>
              </small>
            {% endfor %}
            </div>
        {% endif %}
      {% endwith %}-->
    </div>
  </div>
</div>

oplash/templates/oplash/articles/partials/article1.html
<div class="article-preview">
  <div class="article-meta">
    <a href="{{ article.author.get_absolute_url }}">
      {% if article.author.image %}
        <img src="{{ article.author.image }}" width="32px" height="100%" alt="author image" />
      {% else %}
        <img src="https://api.realworld.io/images/smiley-cyrus.jpeg" width="32px" height="100%" alt="author image" />
      {% endif %}
    </a>
    <div class="info">
      <a href="{{ article.author.get_absolute_url }}" class="author">
        <span>{{ article.author.get_full_name }}</span>
      </a>
      <span class="date">{{ article.created|date:"F j, Y" }}</span>
    </div>
    {% include "realworld/articles/partials/small_favorite_btn.html" with num_favorites=article.num_favorites is_favorite=article.is_favorite %}
  </div>
  <div class="preview-link">
    <h1>{{ article.title }}</h1>
    <p>{{ article.summary }}</p>
    <a href="{{ article.get_absolute_url }}">Read more...</a>
    {% with tags=article.tags.all %}
      {% if tags %}
        <ul class="tag-list">
          {% for tag in tags %}
            <li class="tag-default tag-pill tag-outline">
              <a href="{% url 'articles:list' %}?tag={{ tag.name }}">{{ tag }}</a>
            </li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
  </div>
</div>

oplash/templates/oplash/articles/partials/favorite_btn.html
{% if user.is_authenticated %}
  <form action="{% url 'articles:favorite' article.id %}" method="post" style="display:inline-block">
    {% csrf_token %}
    <button type="submit" class="btn {% if is_favorite %}btn-secondary{% else %}btn-outline-secondary{% endif %} btn-sm">
      <span>
        <i class="bi-heart"></i>
      </span>
      <span>{{ is_favorite|yesno:'Unfavorite Article,Favorite Article' }}</span>
      <span class="counter">({{ num_favorites }})</span>
    </button>
  </form>
{% else %}
  <a href="{% url 'login' %}" class="btn btn-sm btn-outline-secondary">
    <span>
      <i class="bi-heart"></i>
    </span>
    <span>Favorite Article</span>
    <span>({{ num_favorites }})</span>
  </a>
{% endif %}

oplash/templates/oplash/articles/partials/small_favorite_btn.html
{% if user == article.author %}
  <button class="btn btn-outline-secondary btn-sm pull-xs-right" disabled>
    <span>
      <i class="ion-heart"></i>
    </span>
    <span>{{ num_favorites }}</span>
  </button>
{% elif user.is_authenticated %}
  <form action="{% url 'articles:favorite' article.id %}" method="post" style="display:contents">
    {% csrf_token %}
    <button type="submit" class="btn {% if is_favorite %}btn-secondary{% else %}btn-outline-primary{% endif %} btn-sm pull-xs-right" title="{{ is_favorite|yesno:'Unfavorite Article,Favorite Article' }}">
      <span>
        <i class="ion-heart"></i>
      </span>
      <span>{{ num_favorites }}</span>
    </button>
  </form>
{% else %}
  <a href="{% url 'login' %}" class="btn btn-outline-secondary btn-sm pull-xs-right">
    <span>
      <i class="ion-heart"></i>
    </span>
    <span>{{ num_favorites }}</span>
  </a>
{% endif %}