oplash/apps/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import ProfileFollowView, ProfileView, RegisterView, SettingView

urlpatterns = [
    path(
        "register/",
        RegisterView.as_view(redirect_authenticated_user=True),
        name="register",
    ),
    path("login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("settings/", SettingView.as_view(), name="settings"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path("profile/follow/<int:pk>/", ProfileFollowView.as_view(), name="follow"),
]

oplash/apps/articles/urls.py
from django.urls import path

from .views import (
    ArticleCreateView,
    ArticleDeleteView,
    ArticleDetailView,
    ArticleFavoriteView,
    ArticleListView,
    ArticleUpdateView,
)
from .views import Search

app_name = "articles"

urlpatterns = [
    path("", ArticleListView.as_view(), name="list"),
    path("new/", ArticleCreateView.as_view(), name="create"),
    path(
        "article/<int:pk>/<slug:slug>/",
        ArticleDetailView.as_view(),
        name="detail",
    ),
    path(
        "article/edit/<int:pk>/",
        ArticleUpdateView.as_view(),
        name="edit",
    ),
    path(
        "article/delete/<int:pk>/",
        ArticleDeleteView.as_view(),
        name="delete",
    ),
    path(
        "article/favorite/<int:pk>/",
        ArticleFavoriteView.as_view(),
        name="favorite",
    ),
    
    path("search/", Search, name='search'),
]

oplash/apps/comments/urls.py
from django.urls import path

from .views import CommentDeleteView

app_name = "comments"

urlpatterns = [path("delete/<int:pk>/", CommentDeleteView.as_view(), name="delete")]

oplash/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from oplash.apps.articles.views import Search
from filebrowser.sites import site
from django_comments.feeds import LatestCommentFeed

urlpatterns = [
     path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),
    path("", include("oplash.apps.articles.urls")),
    path("", include("oplash.apps.accounts.urls")),
    path("comments/", include("oplash.apps.comments.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path("search/", Search, name='search'),
    path('comments/', include('django_comments.urls')),
    path('feeds/latest/', LatestCommentFeed()),
]

"""if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]"""

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oplash/apps/accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.urls import reverse


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError("The Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    # remove default fields
    username = None
    first_name = None
    last_name = None

    email = models.EmailField("Email address", unique=True)
    name = models.CharField(max_length=60)
    bio = models.TextField(blank=True)
    image = models.ImageField()

    following = models.ManyToManyField(
        "self", blank=True, related_name="followers", symmetrical=False
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("profile", args=[self.id])

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

oplash/apps/comments/models.py
from django.conf import settings
from django.db import models

from oplash.apps.articles.models import Article


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    content = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content[:50]

oplash/apps/core/models.py
from django.db import models

# Create your models here.

oplash/apps/accounts/forms.py
from django.contrib.auth import password_validation
from django.forms import CharField, ModelForm, PasswordInput

from .models import User


class UserCreationForm(ModelForm):
    password = CharField(
        label="Password",
        strip=False,
        widget=PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )

    class Meta:
        model = User
        fields = ["email", "name"]

    def save(self, commit: bool = True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class SettingsForm(ModelForm):
    password = CharField(
        label="Password",
        strip=False,
        required=False,
        widget=PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )

    class Meta:
        model = User
        fields = ["email", "name", "bio", "image"]

    def save(self, commit: bool = True):
        user = super().save(commit=False)
        if self.cleaned_data["password"]:
            user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

oplash/apps/articles/forms.py
from dataclasses import fields
from django import forms

from .models import Article

from tinymce.widgets import TinyMCE


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class ArticleForm(forms.ModelForm):
    
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows':20}
            )
    )
    class Meta:
        model = Article
        fields = '__all__'

"""
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "summary", "content", "tags", "featured", "thumbnail", "next_article", "previous_article", "status"]
        widgets = {"summary": forms.TextInput()}
"""

oplash/apps/comments/forms.py
from django.forms import ModelForm

from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

oplash/apps/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import CreateView, ListView, UpdateView

from oplash.apps.articles.models import Article

from .forms import SettingsForm, User, UserCreationForm


class ProfileView(ListView):
    context_object_name = "articles"
    template_name = "oplash/accounts/profile.html"

    def get_queryset(self):
        profile = get_object_or_404(User, pk=self.kwargs["pk"])
        articles = (
            Article.objects.select_related("author")
            .with_favorites(self.request.user)
            .prefetch_related("tags")
            .order_by("-created")
        )

        if "favorites" in self.request.GET:
            return articles.filter(is_favorite=True)

        return articles.filter(author=profile)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = get_object_or_404(User, pk=self.kwargs["pk"])
        context["profile"] = profile
        context["is_following"] = profile.following.filter(
            pk=self.request.user.id
        ).exists()
        return context


class SettingView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = SettingsForm
    template_name = "oplash/accounts/settings.html"

    def get_object(self):
        return get_object_or_404(User, id=self.request.user.id)


class RegisterView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = "registration/register.html"
    redirect_authenticated_user = False

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a register page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        valid = super().form_valid(form)
        login(self.request, self.object)
        return valid

    def get_success_url(self):
        return '/'


class ProfileFollowView(LoginRequiredMixin, UpdateView):
    fields = ["following"]
    http_method_names = ["post"]

    def get_queryset(self, **kwargs):
        return User.objects.filter(pk=self.kwargs["pk"]).exclude(
            pk=self.request.user.id
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.following.filter(id=request.user.id).exists():
            self.object.following.remove(request.user)
        else:
            self.object.following.add(request.user)

        return redirect(self.object.get_absolute_url())

oplash/apps/articles/views.py
from multiprocessing import context
from turtle import title
from django.forms import SlugField
from django.shortcuts import redirect
from django.test import tag
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)


from django.db.models import Q
from taggit.models import Tag
from django.shortcuts import render
from oplash.apps.comments.forms import Comment, CommentForm
from oplash.apps.core.mixins import AuthorRequiredMixin, LoginRequiredMixin

from .forms import Article, ArticleForm

def Search(request):
    template_name = "oplash/articles/search_results.html"
    queryset = Article.objects.all()
    query = request.GET.get('s')
    if query:
        queryset = queryset.filter(Q(title__icontains=query) | Q(summary__icontains=query)).distinct()

    context ={
        "queryset": queryset
    }
  
    return render(request, template_name, context)


class ArticleListView(ListView):
    context_object_name = "articles"
    template_name = "oplash/articles/article_list.html"

    def get_queryset(self):
        queryset = (
            Article.objects.select_related("author")
            .get_published()
            .with_favorites(self.request.user)
            .prefetch_related("tags")
            .order_by("-created")
        )

        if tag := self.request.GET.get("tag"):
            return queryset.filter(tags__name__in=[tag])

        if self.request.user.is_authenticated and "own" in self.request.GET:
            return queryset.filter(author=self.request.user)

        return queryset
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tags"] = Tag.objects.all()
        context['latest'] = Article.objects.get_published().order_by('-created')[0:4]
        context['featured'] = Article.objects.get_published().filter(featured=True).order_by('featured')[0:2]
        return context


class ArticleDetailView(DetailView):
    context_object_name = "article"
    template_name = "oplash/articles/article_detail.html"

    def get_queryset(self):
        queryset = Article.objects.select_related("author").with_favorites(
            self.request.user
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        is_following = self.object.author.following.filter(
            pk=self.request.user.id
        ).exists()
        comments = (
            Comment.objects.filter(article=self.kwargs["pk"])
            .select_related("author")
            .order_by("-created")
        )

        context["is_following"] = is_following
        context["tags"] = Tag.objects.all()
        context["comments"] = comments
        context["comment_form"] = CommentForm()
        context['related']=Article.objects.prefetch_related("tags").order_by("?")[0:4]
        return context

    def post(self, request, *args, **kwargs):
        comment = Comment(
            content=request.POST.get("content"),
            author=self.request.user,
            article=self.get_object(),
        )
        comment.save()
        return self.get(self, request, *args, **kwargs)


class ArticleCreateView(AuthorRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm
    template_name = "oplash/articles/article_form.html"

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        article.save()

        # save tags
        form.save_m2m()

        return super().form_valid(form)


class ArticleUpdateView(AuthorRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = "oplash/articles/article_form.html"


class ArticleDeleteView(AuthorRequiredMixin, DeleteView):
    model = Article
    success_url = "/"


class ArticleFavoriteView(LoginRequiredMixin, UpdateView):
    fields = ["favorites"]
    http_method_names = ["post"]

    def get_queryset(self):
        return Article.objects.select_related("author").exclude(
            author=self.request.user
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.favorites.filter(id=request.user.id).exists():
            self.object.favorites.remove(request.user)
        else:
            self.object.favorites.add(request.user)

        return redirect(self.object.get_absolute_url())

oplash/apps/comments/views.py
from django.views.generic import DeleteView

from oplash.apps.core.mixins import AuthorRequiredMixin

from .models import Comment


class CommentDeleteView(AuthorRequiredMixin, DeleteView):
    model = Comment
    success_url = "/"

oplash/apps/core/views.py
from django.shortcuts import render

# Create your views here.

oplash/templates/oplash/articles/article_detail1.html
{% extends "base.html" %}

{% block content %}
<div class="article-page">
  <div class="banner">
    <div class="container">
      <h1>{{ article.title }}</h1>
      <div class="article-meta">
        {% if article.author.image %}
          <img src="{{ article.author.image }}" width="32px" height="100%" alt="author image" />
        {% else %}
          <img src="https://api.realworld.io/images/smiley-cyrus.jpeg" width="32px" height="100%" alt="author image" />
        {% endif %}
        <div class="info">
          <a href="{{ article.author.get_absolute_url }}" class="author">
            <span>{{ article.author.get_full_name }}</span>
          </a>
          <span class="date">{{ article.created|date:"F j, Y" }}</span>
        </div>
        {% if user == article.author %}
          <a href="{% url 'articles:edit' article.id %}" class="btn btn-outline-secondary btn-sm">
            <span>
              <i class="ion-edit"></i>
            </span>
            <span>Edit Article</span>
          </a>
          <form action="{% url 'articles:delete' article.id %}" method="post" style="display:inline-block" up-confirm="Really delete?">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger btn-sm">
              <span>
                <i class="ion-trash-a"></i>
              </span>
              <span>Delete Article</span>
            </button>
          </form>
        {% else %}
          {% include "realworld/accounts/partials/follow_btn.html" with followed=article.author %}
          {% include "realworld/articles/partials/favorite_btn.html" with is_favorite=article.is_favorite num_favorites=article.num_favorites %}
        {% endif %}
      </div>
    </div>
  </div>

  <div class="container page">
    <div class="row article-content">
      <div class="col-md-12">
        <div>
          <p>{{ article.summary }}</p>
          {{ article.as_markdown|safe }}
        </div>
        {% with tags=article.tags.all %}
          {% if tags %}
            <ul class="tag-list">
              {% for tag in tags %}
                <li class="tag-default tag-pill tag-outline">
                  <a href="{% url 'articles:list' %}?tag={{ tag.name }}">{{ tag }}</a>
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}
      </div>
    </div>
    <hr />
    <div class="article-actions">
      <div class="article-meta">
        {% if article.author.image %}
          <img src="{{ article.author.image }}" width="32px" height="100%" alt="author image" />
        {% else %}
          <img src="https://api.realworld.io/images/smiley-cyrus.jpeg" width="32px" height="100%" alt="author image" />
        {% endif %}
        <div class="info">
          <a href="{{ article.author.get_absolute_url }}" class="author">
            <span>{{ article.author.get_full_name }}</span>
          </a>
          <span class="date">{{ article.created|date:"F j, Y" }}</span>
        </div>
        {% if user == article.author %}
          <a href="{% url 'articles:edit' article.id %}" class="btn btn-outline-secondary btn-sm">
            <span>
              <i class="ion-edit"></i>
            </span>
            <span>Edit Article</span>
          </a>
          <form action="{% url 'articles:delete' article.id %}" method="post" style="display:inline-block" up-confirm="Really delete?">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger btn-sm">
              <span>
                <i class="ion-trash-a"></i>
              </span>
              <span>Delete Article</span>
            </button>
          </form>
        {% else %}
          {% include "realworld/accounts/partials/follow_btn.html" with followed=article.author %}
          {% include "realworld/articles/partials/favorite_btn.html" with is_favorite=article.is_favorite num_favorites=article.num_favorites %}
        {% endif %}
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8 offset-md-2">
        {% if user.is_authenticated %}
          <div>
            {% include "realworld/comments/comment_form.html" with form=comment_form %}
          </div>
        {% else %}
          <p style="text-align:center">
            <a href="{% url 'login' %}">Sign in</a>
            or
            <a href="{% url 'register' %}">sign up</a>
            to add comments on this article.
          </p>
        {% endif %}
        {% for comment in comments %}
          <div>
            {% include "realworld/comments/comment.html" %}
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

oplash/templates/oplash/articles/article_list.html
{% extends "base.html" %}
{% load static %}
{% load comments %}
{% block content %}

<style>
  .text-sm {
    font-size: 0.7rem !important;
  }

  .reset-anchor {
    color: inherit;
    transition: all 0.3s;
  }

  .lh-sm {
    line-height: 1.25 !important;
  }

  .mb-0 {
    margin-bottom: 0 !important;
  }

  .ms-3 {
    margin-left: 1rem !important;
  }

  .card-body {
    flex: 1 1 auto;
    padding: 1rem 1rem;
  }

  .p-0 {
    padding: 0 !important;
  }

  h6,
  .h6 {
    font-size: 1rem;
  }

  .card {
    border: 0 solid rgba(0, 0, 0, .125);
    border-radius: 0;
  }

  .card-text-responsive {
    font-size: calc(100% + 1vw + 1vh);
  }
</style>

<header class="bg-dark py-5 mb-5">
  <div class="container px-5">

    <div class="row gx-5 align-items-center justify-content-center">
      <div class="col-lg-8 col-xl-7 col-xxl-6">

        <div class="my-5 text-center text-xl-start">
          <h1 class="display-5 fw-bolder mb-2"><a class="text-white" href="">Stay Curious | Learn Something New</a></h1>
          <p class="lead fw-normal text-white-50 mb-4">Algorithms an Time Parallelization. An intrinsic approach to an
            indepth undestanding of algorithms and their applications and their role in new emergin technologies.</p>
          <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
            <header class="post-header" style="margin-bottom: 10px;">

              <div class="category">
                <!--<a  class="text-white" href="{% url 'articles:list' %}?tag={{ tag.name }}" class="tag-pill tag-default">{{ tag }}</a>-->
              </div>

              <!--<h4 class="h4"><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h4>-->
            </header>
          </div>
        </div>
      </div>
      <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded-3 my-5"
          src="{% static 'img/ai-imag02.jpg' %}" alt="..."></div>
    </div>

  </div>
</header>
<section>
  <div class="container">
    <div class="row d-flex aligne-items-stretch">
      <h4 class="text-center"> Aquiring knowledge is Inherently rewarding and pleasurable</h4>
      <div class="my-3 py-3 d-flex">
        <div class="col-md-6 col-lg-8">
          <h4 class="">Posts</h4>
        </div>
        <!-- Search bar -->
        <div class="col-md-6 col-lg-4">
          <form action="{% url 'search' %}" class="d-flex" role="search">
            <input class="form-control me-2" type="text" name="s" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-primary" type="submit"><i class="bi-search" role="img" aria-label="Search"></i></button>
          </form>
        </div>
      </div>

      <div class="col-lg-9">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for article in articles %}
          {% include "oplash/articles/partials/article.html" %}
          {% empty %}
          <div class="article-preview">No articles are here... yet.</div>
          {% endfor %}

        </div>
        <!--

    
          <div class="album bg-white">
         
          
              <h2 class="p-3 my-5 bg-dark text-white"> Featured Articles</h2>
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
                  {% for article in featured %}
                  <div class="col-lg-6 col-md-6">
                    <div class="card shadow-sm">
                      <div class="card-header d-flex justify-content-between align-items-center">
                        {% get_comment_count for article as comment_count %}
                
                        <div class="comment"><i class="bi-chat"></i>  {{ comment_count}}</div>
                        <small class="text-muted">{{article.get_readtime}} mins</small>
                      </div>
                      <a class="text-black" href="{{ article.get_absolute_url }}"><img class="bd-placeholder-img card-img-top" src="{{ article.thumbnail.url }}" width="100%" height="225" alt="article image"></a>
                  
                      <div class="card-body">
                        <h4 class="card-text"><a class="text-black" href="{{ article.get_absolute_url }}">{{ article.title | truncatechars:45}}</a></h4>
                        <p class="card-text">{{ article.summary | truncatechars:70 }} </p>
                      
                       <footer class="post-footer d-flex justify-content-between align-items-center" style="margin-top: 30px;">
                        <a class="author d-flex align-items-center flex-wrap">
                          <div class="avater" style="max-width: 30px;
                        min-width: 30px;
                        height: 30px;
                        overflow: hidden;
                        border-radius: 50%;
                        margin-right: 3px;">
                           {% if article.author.image %}
                
                           <div class=""><img class="rounded-circle" src="{{ article.author.image.url }}" width="30" height="30" style="border:1px solid gray">
                             <small>{{article.author}}</small>
                           </div>
                             {% else %}
                         
                             <div><img class="rounded-circle" src="{% static '/img/profile.png' %}" width="30" height="30" alt="user profile image">
                               <span>{{article.author}}</span>
                             </div>
                               {% endif %}
                
                        </div>
                      
                        <div class="title"><span><em> {{article.author}} </em></span></div>
                        </a>
                        <div class="date"> <i class="bi-clock"></i> {{ article.created | timesince}} ago</div>
                      
                
                        <div class="btn-group">
                      
                          {% include "oplash/articles/partials/small_favorite_btn.html" with num_favorites=article.num_favorites is_favorite=article.is_favorite %}
                          
                        </div>
                
                      </footer>
                
                      </div>
                    </div>
                  </div>
                {% empty %}
                  <div class="article-preview">No articles are here... yet.</div>
                {% endfor %}
      
            
            </div>
            </div> 
 
          -->

        <div class="row my-4 p-3">
          <img class="img-fluid mx-auto d-block" src="{% static 'img/728x90-blue.png' %}" alt="Addvertisement">
        </div>

      </div>
      <!--side bar-->
      <div class="col-lg-3 border">
        <div class="card mb-4 py-lg-4">
          <h2 class="h5">Featured Post</h5>
          <div class="card-body text-center">
           
              {% for obj in featured %}
              <a href="{{obj.get_absolute_url}}" ><img class="rounded-cire mb-1" src="{{obj.thumbnail.url}}" alt="..." width="100"></a>
              <h6><a href="{{obj.get_absolute_url}}" class="text-dark"> {{obj.title}} </a></h6>
              <p class="text-sm text-muted">{{obj.summary}}</p>
              <ul class="list-inline small mb-3 text-dark">
                <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="bi-facebook"></i></a></li>
                <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="bi-twitter"></i></a></li>
                <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="bi-github"></i></a></li>
                <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="bi-instagram"></i></a></li>
                <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="bi-linkedin"></i></a></li>
                <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="bi-youtube"></i></a></li>
              </ul>
              {% endfor %}
          </div>
        </div>

        <div class="card my-4">
          <div class="card-body p-0">
            <h5 class="mb-3">Recent Posts</h5>
            {% for object in latest %}
            <div class="d-flex mb-3">
              <a class="flex-shrink-0" href="{{object.get_absolute_url}}"> <img class="img-fluid"
                  src="{{ object.thumbnail.url }}" width="70" alt="article categories"></a>
              <div class="ms-3">
                <h6><a class="reset-anchor" href="{{object.get_absolute_url}}"> {{object.title | truncatechars:70}}</a>
                </h6>
                <p class="text-sm text-muted mb-0 lh-sm">{{object.summary | truncatechars:70}}</p>
              </div>
            </div>

            {% endfor %}
          </div>
        </div>

        <div class="my-4">
          <h5 class="">All Topics </h5>
          {% for tag in tags %}
          <a href="{% url 'articles:list' %}?tag={{ tag.name }}" class="badge badge-pill badge-secondary text-black">
            {{ tag }}
          </a>
          {% endfor %}
        </div>

        <div class="align-items-center my-4" style="border: 1px solid gray;">
          <img class="img-fluid mx-auto d-block" src="{% static 'img/320x250.png' %}" alt="Addvertisement">
        </div>
      </div>
      <!--End Side Bar-->
    </div>
  </div>
  <!--End Container -->
</section>


<section class="mb-5" style="background-color:#3e3eff; ">
  <div class="container">
    <div
      class="d-flex align-items-center justify-content-between flex-column flex-xl-row text-center text-xl-start py-5">
      <div class="mb-4 mb-xl-0">
        <div class="fs-3 fw-bold text-white">Subscribe for new posts.</div>
        <div class="text-white-50">Receive our newsletters and latest updates.</div>
      </div>
      <div class="ms-xl-4">
        <div class="input-group mb-2">
          <input class="form-control" type="text" placeholder="Email address..." aria-label="Email address..."
            aria-describedby="button-newsletter">
          <button class="btn btn-outline-light" id="button-newsletter" type="button">Sign up</button>
        </div>
        <div class="small text-white-50">We care about privacy, and will never share your data.</div>
      </div>
    </div>
  </div>
</section>



{% endblock%}