oplash/apps/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import ProfileFollowView, ProfileView, RegisterView, SettingView

urlpatterns = [
    path(
        "register/",
        RegisterView.as_view(redirect_authenticated_user=True),
        name="register",
    ),
    path("login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("settings/", SettingView.as_view(), name="settings"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path("profile/follow/<int:pk>/", ProfileFollowView.as_view(), name="follow"),
]

oplash/apps/articles/urls.py
from django.urls import path

from .views import (
    ArticleCreateView,
    ArticleDeleteView,
    ArticleDetailView,
    ArticleFavoriteView,
    ArticleListView,
    ArticleUpdateView,
)
from .views import Search

app_name = "articles"

urlpatterns = [
    path("", ArticleListView.as_view(), name="list"),
    path("new/", ArticleCreateView.as_view(), name="create"),
    path(
        "article/<int:pk>/<slug:slug>/",
        ArticleDetailView.as_view(),
        name="detail",
    ),
    path(
        "article/edit/<int:pk>/",
        ArticleUpdateView.as_view(),
        name="edit",
    ),
    path(
        "article/delete/<int:pk>/",
        ArticleDeleteView.as_view(),
        name="delete",
    ),
    path(
        "article/favorite/<int:pk>/",
        ArticleFavoriteView.as_view(),
        name="favorite",
    ),
    
    path("search/", Search, name='search'),
]

oplash/apps/comments/urls.py
from django.urls import path

from .views import CommentDeleteView

app_name = "comments"

urlpatterns = [path("delete/<int:pk>/", CommentDeleteView.as_view(), name="delete")]

oplash/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from oplash.apps.articles.views import Search
from filebrowser.sites import site
from django_comments.feeds import LatestCommentFeed

urlpatterns = [
     path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),
    path("", include("oplash.apps.articles.urls")),
    path("", include("oplash.apps.accounts.urls")),
    path("comments/", include("oplash.apps.comments.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path("search/", Search, name='search'),
    path('comments/', include('django_comments.urls')),
    path('feeds/latest/', LatestCommentFeed()),
]

"""if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]"""

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oplash/apps/accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.urls import reverse


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError("The Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    # remove default fields
    username = None
    first_name = None
    last_name = None

    email = models.EmailField("Email address", unique=True)
    name = models.CharField(max_length=60)
    bio = models.TextField(blank=True)
    image = models.ImageField()

    following = models.ManyToManyField(
        "self", blank=True, related_name="followers", symmetrical=False
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("profile", args=[self.id])

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

oplash/apps/comments/models.py
from django.conf import settings
from django.db import models

from oplash.apps.articles.models import Article


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    content = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content[:50]

oplash/apps/core/models.py
from django.db import models

# Create your models here.

oplash/apps/accounts/forms.py
from django.contrib.auth import password_validation
from django.forms import CharField, ModelForm, PasswordInput

from .models import User


class UserCreationForm(ModelForm):
    password = CharField(
        label="Password",
        strip=False,
        widget=PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )

    class Meta:
        model = User
        fields = ["email", "name"]

    def save(self, commit: bool = True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class SettingsForm(ModelForm):
    password = CharField(
        label="Password",
        strip=False,
        required=False,
        widget=PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )

    class Meta:
        model = User
        fields = ["email", "name", "bio", "image"]

    def save(self, commit: bool = True):
        user = super().save(commit=False)
        if self.cleaned_data["password"]:
            user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

oplash/apps/articles/forms.py
from dataclasses import fields
from django import forms

from .models import Article

from tinymce.widgets import TinyMCE


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class ArticleForm(forms.ModelForm):
    
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows':20}
            )
    )
    class Meta:
        model = Article
        fields = '__all__'

"""
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "summary", "content", "tags", "featured", "thumbnail", "next_article", "previous_article", "status"]
        widgets = {"summary": forms.TextInput()}
"""

oplash/apps/comments/forms.py
from django.forms import ModelForm

from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

oplash/apps/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import CreateView, ListView, UpdateView

from oplash.apps.articles.models import Article

from .forms import SettingsForm, User, UserCreationForm


class ProfileView(ListView):
    context_object_name = "articles"
    template_name = "oplash/accounts/profile.html"

    def get_queryset(self):
        profile = get_object_or_404(User, pk=self.kwargs["pk"])
        articles = (
            Article.objects.select_related("author")
            .with_favorites(self.request.user)
            .prefetch_related("tags")
            .order_by("-created")
        )

        if "favorites" in self.request.GET:
            return articles.filter(is_favorite=True)

        return articles.filter(author=profile)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = get_object_or_404(User, pk=self.kwargs["pk"])
        context["profile"] = profile
        context["is_following"] = profile.following.filter(
            pk=self.request.user.id
        ).exists()
        return context


class SettingView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = SettingsForm
    template_name = "oplash/accounts/settings.html"

    def get_object(self):
        return get_object_or_404(User, id=self.request.user.id)


class RegisterView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = "registration/register.html"
    redirect_authenticated_user = False

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a register page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        valid = super().form_valid(form)
        login(self.request, self.object)
        return valid

    def get_success_url(self):
        return '/'


class ProfileFollowView(LoginRequiredMixin, UpdateView):
    fields = ["following"]
    http_method_names = ["post"]

    def get_queryset(self, **kwargs):
        return User.objects.filter(pk=self.kwargs["pk"]).exclude(
            pk=self.request.user.id
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.following.filter(id=request.user.id).exists():
            self.object.following.remove(request.user)
        else:
            self.object.following.add(request.user)

        return redirect(self.object.get_absolute_url())

oplash/apps/articles/views.py
from multiprocessing import context
from turtle import title
from django.forms import SlugField
from django.shortcuts import redirect
from django.test import tag
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)


from django.db.models import Q
from taggit.models import Tag
from django.shortcuts import render
from oplash.apps.comments.forms import Comment, CommentForm
from oplash.apps.core.mixins import AuthorRequiredMixin, LoginRequiredMixin

from .forms import Article, ArticleForm

def Search(request):
    template_name = "oplash/articles/search_results.html"
    queryset = Article.objects.all()
    query = request.GET.get('s')
    if query:
        queryset = queryset.filter(Q(title__icontains=query) | Q(summary__icontains=query)).distinct()

    context ={
        "queryset": queryset
    }
  
    return render(request, template_name, context)


class ArticleListView(ListView):
    context_object_name = "articles"
    template_name = "oplash/articles/article_list.html"

    def get_queryset(self):
        queryset = (
            Article.objects.select_related("author")
            .get_published()
            .with_favorites(self.request.user)
            .prefetch_related("tags")
            .order_by("-created")
        )

        if tag := self.request.GET.get("tag"):
            return queryset.filter(tags__name__in=[tag])

        if self.request.user.is_authenticated and "own" in self.request.GET:
            return queryset.filter(author=self.request.user)

        return queryset
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tags"] = Tag.objects.all()
        context['latest'] = Article.objects.get_published().order_by('-created')[0:4]
        context['featured'] = Article.objects.get_published().filter(featured=True).order_by('featured')[0:2]
        return context


class ArticleDetailView(DetailView):
    context_object_name = "article"
    template_name = "oplash/articles/article_detail.html"

    def get_queryset(self):
        queryset = Article.objects.select_related("author").with_favorites(
            self.request.user
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        is_following = self.object.author.following.filter(
            pk=self.request.user.id
        ).exists()
        comments = (
            Comment.objects.filter(article=self.kwargs["pk"])
            .select_related("author")
            .order_by("-created")
        )

        context["is_following"] = is_following
        context["tags"] = Tag.objects.all()
        context["comments"] = comments
        context["comment_form"] = CommentForm()
        context['related']=Article.objects.prefetch_related("tags").order_by("?")[0:4]
        return context

    def post(self, request, *args, **kwargs):
        comment = Comment(
            content=request.POST.get("content"),
            author=self.request.user,
            article=self.get_object(),
        )
        comment.save()
        return self.get(self, request, *args, **kwargs)


class ArticleCreateView(AuthorRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm
    template_name = "oplash/articles/article_form.html"

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        article.save()

        # save tags
        form.save_m2m()

        return super().form_valid(form)


class ArticleUpdateView(AuthorRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = "oplash/articles/article_form.html"


class ArticleDeleteView(AuthorRequiredMixin, DeleteView):
    model = Article
    success_url = "/"


class ArticleFavoriteView(LoginRequiredMixin, UpdateView):
    fields = ["favorites"]
    http_method_names = ["post"]

    def get_queryset(self):
        return Article.objects.select_related("author").exclude(
            author=self.request.user
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.favorites.filter(id=request.user.id).exists():
            self.object.favorites.remove(request.user)
        else:
            self.object.favorites.add(request.user)

        return redirect(self.object.get_absolute_url())

oplash/apps/comments/views.py
from django.views.generic import DeleteView

from oplash.apps.core.mixins import AuthorRequiredMixin

from .models import Comment


class CommentDeleteView(AuthorRequiredMixin, DeleteView):
    model = Comment
    success_url = "/"

oplash/apps/core/views.py
from django.shortcuts import render

# Create your views here.

oplash/templates/partials/carosel.html
{% load static %}
<style>
.bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }

</style>
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="bd-placeholder-img" src="{% static 'img/ai-image03-copy.jpg' %}" width="100%" height="100%">

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Example headline.</h1>
            <p>Some representative placeholder content for the first slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="bd-placeholder-img" src="{% static 'img/ai-image05.jpg' %}" width="100%" height="10%">  
        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="bd-placeholder-img" src="{% static 'img/ai-image07.jpg' %}" width="100%" height="100%">  
        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

oplash/templates/partials/footer.html
    <footer class="py-3 footer">
   <!--   <div class="row">
        <div class="col-2">
          <h5>Section</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-black">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-black">Features</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-black">Pricing</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-black">FAQs</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-black">About</a></li>
          </ul>
        </div>
  
        <div class="col-2">
          <h5>Section</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-black">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-black">Features</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-black">Pricing</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-black">FAQs</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-black">About</a></li>
          </ul>
        </div>
  
        <div class="col-2">
          <h5>Social</h5>
          <ul class="social-list list-inline mb-0">
            <li class="list-inline-item"><i class="bi-github" role="img" aria-label="GitHub"></i></li>
              <li class="list-inline-item"><i class="bi-linkedin" role="img" aria-label="linkedin" style="color: blue;"></i></li>
              <li class="list-inline-item"><i class="bi-youtube"  role="img" aria-label="youtube" style="color: red;" ></i></li>
      </ul>
        </div>
  
        <div class="col-4 offset-1">
          <form>
            <h5>Subscribe to our newsletter</h5>
            <p>Monthly digest of whats new and exciting from us.</p>
            <div class="d-flex w-100 gap-2">
              <label for="newsletter1" class="visually-hidden">Email address</label>
              <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
              <button class="btn btn-primary" type="button">Subscribe</button>
            </div>
          </form>
        </div>
      </div>
    -->
    <div class="container">
      <div class="d-flex justify-content-between py-3 my-3 border-top">
        <p><small>&copy; 2022 Oplash.com, Inc. All rights reserved.</small></p>
        <ul class="list-unstyled d-flex">
          <li class="ms-3"><a class="link-dark" href="https://github.com/kibir"><svg class="bi" width="24" height="24"><use xlink:#twitter/></svg><i class="bi-github" role="img" aria-label="GitHub"></i></a></li>
          <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg><i class="bi-linkedin" role="img" aria-label="LinkedIn"></i></a></li>
          <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg><i class="bi-facebook" role="img" aria-label="Facebook"></i></a></li>
        </ul>
      </div>
      </div>
    </footer>

oplash/templates/partials/footer1.html
<footer>
  <div>
    <a href="https://www.oplash.com" target="_blank" style="position:fixed;bottom:0;width:100%;background:linear-gradient(#485563, #29323c);text-align: center;padding:15px;box-shadow:0 5px 5px 5px rgba(0,0,0,0.4);z-index:999;color:#fff;font-size:1.5rem;display:block">
      <i class="ion-social-github"></i>&nbsp;
      <span>www.oplash.com</span>
    </a>
  </div>
</footer>

oplash/templates/partials/header.html
{% load static %}
<header class="header">
    <div class="navbar-fixed-top mb-1" style="background-color: rgb(248, 249, 250); border: 1px solid #eee;">
        <div class="container" style="background-color: rgb(248, 249, 250);">
            <nav class="navbar navbar-expand-lg navbar-light position-relative">
             <a  class="" href="{% url 'articles:list' %}"> <img class="" src="{% static '/img/oplash_logo_dark_100.png' %}" width="70"></a>
               <!-- <h4><a  class="mx-1" href="{% url 'articles:list' %}" style="color: Black; font-weight: 700;">Zetasim</a></h4>-->
       
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarnav" aria-controls="navbarnav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarnav">
                  {% with url_name=request.resolver_match.url_name %}
                  <ul class="navbar-nav ms-lg-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'articles:list' %}">Home <span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'articles:list' %}">Videos <span class="sr-only"></span></a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'articles:create' %}">New Aricle <span class="{% if url_name == 'create' %} active{% endif %}"></span></a>
                    </li>
                  
                  
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle-false" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        
                            {% if user.image %}
                              <img src="{{ user.image.url}}" class="rounded-circle" width="26px" height="100%" alt="author image" />
                            
                            {% else %}
                              <img src="{% static 'img/profile.png' %}" class="rounded-circle" width="25px" height="25px" alt="author image"  />
                            {% endif %}
                            <small><span>{{ user.name }}</span></small>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                          <li><a href="{{ user.get_absolute_url }}" class=" dropdown-item {% if url_name == 'profile' %} active{% endif %}">Profile</a></li>
                          <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                          <li>
                            <hr class="dropdown-divider">
                          </li>
                          <li>  <a href="{% url 'settings' %}" class="dropdown-item">Settings</a></li>
                        </ul>
                      
                      </li>

                    {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'login' %}">Sign In</a>
                    </li>
                    {% endif %}
                  </ul>
                  {% endwith %}
                  <span class="navbar-text slid-line"> </span>
                </div>
              </nav>
        </div>

    </div>
   <!-- <div class="intro-header py-5 text-white" style="background-color: gray;">
        <div class="container position-relative">
            <div class="row g-2 g-lg-3">
                <div class="col12 col-md-auto">
                    <img  src="{% static '/img/intro-image.png' %}" alt="..." class="img-intro align-center img-thumbnail" width="200" height="200" style="margin-right: 1.5rem !important;">
                </div>
                <div class="col align-self-center">
                    <h2> Zetasim machine learning hub</h2>
                    <div class="page-heading tag-line mb-3">
                        This is all you want to know about machine learning and the future of web development
                        <br class="">
                        Here everyting you want about web development
                    </div>
                </div>
            </div>
        </div>

    </div>-->
</header>

oplash/templates/partials/header1.html
<header>
  <nav class="navbar navbar-light">
    <div class="container">
      <a href="{% url 'articles:list' %}" class="navbar-brand">zetasim</a>
      {% with url_name=request.resolver_match.url_name %}
        <ul class="nav navbar-nav pull-xs-right">
          <li class="nav-item">
            <a href="{% url 'articles:list' %}" class="nav-link{% if url_name == 'list' %} active{% endif %}">
              Home
            </a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'articles:create' %}" class="nav-link{% if url_name == 'create' %} active{% endif %}">
                <span>
                  <i class="ion-compose"></i>
                </span>
                <span>New Article</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'settings' %}" class="nav-link{% if url_name == 'settings' %} active{% endif %}">
                <span>
                  <i class="ion-gear-a"></i>
                </span>
                <span>Settings</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ user.get_absolute_url }}" class="nav-link{% if url_name == 'profile' %} active{% endif %}">
                {% if user.image %}
                  <img src="{{ user.image }}" class="user-pic" width="26px" height="100%" alt="author image" />
                {% else %}
                  <img src="https://api.realworld.io/images/smiley-cyrus.jpeg" class="user-pic" width="26px" height="100%" alt="author image"  />
                {% endif %}
                <span>{{ user.name }}</span>
              </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link{% if url_name == 'login' %} active{% endif %}">Sign in</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'register' %}" class="nav-link{% if url_name == 'register' %} active{% endif %}">Sign up</a>
            </li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

oplash/templates/partials/hero.html
{% load static %}
<section style="background: url('{% static 'img/ai-image07.jpg' %}')" class="py-5 hero-center hero-size">
    <div class="hero-overlay"></div>
    <div class="container py-5 text-white text-left">
      <h1 class="text-shadow hero-heading">This is Multi</h1>
      <p class="text-shadow lead my-4">Bootstrap Multipurpose Template by <a href="#" class="text-white">Bootstrapious.com</a></p><a href="#" class="btn btn-outline-light btn-sm">Learn More</a>
    </div>
  </section>
  

oplash/templates/partials/latest-header.html
{% load static %}
<header class="bg-dark py-5 mb-5">
    <div class="container px-5">
    
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-lg-8 col-xl-7 col-xxl-6">
               
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-5 fw-bolder mb-2"><a class="text-white" href="">Stay Curious and on Track</a></h1>
                    <p class="lead fw-normal text-white-50 mb-4">Algorithms an Time Parallelization. An intrinsic approach to an indepth undestanding of algorithms and their applications and their role in new emergin technologies</p>
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                        <header class="post-header" style="margin-bottom: 10px;">
                           
                            <div class="category">
                               <!--<a  class="text-white" href="{% url 'articles:list' %}?tag={{ tag.name }}" class="tag-pill tag-default">{{ tag }}</a>-->
                            </div>
                      
                            <!--<h4 class="h4"><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h4>-->
                          </header>
                    </div>
                </div>
            </div>
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded-3 my-5" src="{% static 'img/ai-imag02.jpg' %}"  alt="..."></div>
        </div>
     
    </div>
</header>